import type { Episode } from "../format/episode.js";
import { parseChapters } from "../format/parseChapters.js";
import { parseTimedText } from "./parseTimedText.js";
import { selectTrack, type CaptionTrack, type TrackChoice } from "./selectTrack.js";

/**
 * Identify as the Android client.
 *
 * This is the whole reason this works. The WEB client's caption URLs carry an
 * `exp=xpe` parameter — a Proof-of-Origin gate we cannot satisfy — and serve an
 * empty body. The Android client's URLs carry no such parameter and serve the
 * track normally. Same endpoint, same video; only the claimed client differs.
 */
const ANDROID_CLIENT = {
  clientName: "ANDROID",
  clientVersion: "20.10.38",
  androidSdkVersion: 30,
  hl: "en",
  gl: "US",
} as const;

const PLAYER_URL = "https://www.youtube.com/youtubei/v1/player";

export class NoCaptionsError extends Error {
  constructor(readonly videoId: string) {
    super("This episode has no captions, so there is no transcript to harvest.");
    this.name = "NoCaptionsError";
  }
}

export class NotPlayableError extends Error {}

export interface FetchedEpisode {
  episode: Episode;
  /** Set when the chosen caption track is a compromise. */
  warning?: string;
  trackLanguage: string;
  trackIsAutoGenerated: boolean;
}

/** The body to POST to the player endpoint. Shared so every caller claims the same client. */
export function playerRequest(videoId: string): { url: string; init: RequestInit } {
  return {
    url: PLAYER_URL,
    init: {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Youtube-Client-Name": "3",
        "X-Youtube-Client-Version": ANDROID_CLIENT.clientVersion,
      },
      body: JSON.stringify({ context: { client: ANDROID_CLIENT }, videoId }),
    },
  };
}

/**
 * Choose the caption track from a player response. Pure — separated from the
 * network so the extension can do its fetching inside the page (same-origin)
 * while sharing this logic.
 */
export function pickTrack(payload: PlayerResponse, videoId: string): TrackChoice {
  const status = payload.playabilityStatus?.status;
  if (status && status !== "OK") {
    throw new NotPlayableError(payload.playabilityStatus?.reason ?? `Video is ${status}.`);
  }

  const details = payload.videoDetails;
  if (!details) throw new NotPlayableError("YouTube returned no details for this video.");

  const tracks = payload.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const choice = selectTrack(tracks, details.defaultAudioLanguage ?? undefined);
  if (!choice) throw new NoCaptionsError(videoId);
  return choice;
}

/** Assemble the episode from a player response and its fetched track. Pure. */
export function buildEpisode(
  payload: PlayerResponse,
  xml: string,
  videoId: string,
  choice: TrackChoice,
): FetchedEpisode {
  const details = payload.videoDetails!;
  const cues = parseTimedText(xml);
  if (cues.length === 0) throw new NoCaptionsError(videoId);

  const episode: Episode = {
    title: details.title,
    channel: details.author,
    url: `https://www.youtube.com/watch?v=${videoId}`,
    ...(payload.microformat?.playerMicroformatRenderer?.publishDate
      ? { publishedAt: payload.microformat.playerMicroformatRenderer.publishDate.slice(0, 10) }
      : {}),
    ...(details.lengthSeconds ? { durationSeconds: Number(details.lengthSeconds) } : {}),
    chapters: parseChapters(details.shortDescription ?? ""),
    segments: cues.map((cue) => ({ text: cue.text })),
  };

  return {
    episode,
    ...(choice.warning ? { warning: choice.warning } : {}),
    trackLanguage: choice.track.languageCode,
    trackIsAutoGenerated: choice.track.kind === "asr",
  };
}

/** Fetch an episode directly. Used by the CLI, where no browser origin is involved. */
export async function fetchEpisode(videoId: string): Promise<FetchedEpisode> {
  const { url, init } = playerRequest(videoId);
  const response = await fetch(url, init);
  if (!response.ok) {
    throw new NotPlayableError(`YouTube refused the request (HTTP ${response.status}).`);
  }

  const payload = (await response.json()) as PlayerResponse;
  const choice = pickTrack(payload, videoId);
  const xml = await (await fetch(choice.track.baseUrl)).text();
  return buildEpisode(payload, xml, videoId, choice);
}

interface PlayerResponse {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: {
    title: string;
    author: string;
    lengthSeconds?: string;
    shortDescription?: string;
    defaultAudioLanguage?: string;
  };
  microformat?: { playerMicroformatRenderer?: { publishDate?: string } };
  captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
}
