import { formatForClipboard } from "../format/formatForClipboard.js";
import { playerRequest, pickTrack, buildEpisode, NoCaptionsError, NotPlayableError, } from "../youtube/fetchEpisode.js";
import { videoIdFrom } from "../youtube/videoId.js";
const button = document.getElementById("grab");
const status = document.getElementById("status");
const details = document.getElementById("details");
function say(message, tone) {
    status.textContent = message;
    status.className = tone;
}
/**
 * Fetch from inside the page rather than from the popup.
 *
 * A popup fetch is cross-origin: it carries `Origin: chrome-extension://…` and
 * the user's YouTube cookies, so YouTube sees a logged-in WEB session claiming
 * to be the Android client and answers 403. Running the same request in the
 * page makes it same-origin and it succeeds. The request itself is passed in,
 * so the client identity lives in exactly one place.
 */
async function fetchInPage(tabId, url, init) {
    const [injection] = await chrome.scripting.executeScript({
        target: { tabId },
        world: "MAIN",
        args: [url, init],
        func: async (target, options) => {
            const response = await fetch(target, options);
            return { ok: response.ok, status: response.status, body: await response.text() };
        },
    });
    if (!injection?.result)
        throw new Error("The page did not respond. Try reloading the tab.");
    return injection.result;
}
button.addEventListener("click", async () => {
    button.disabled = true;
    details.textContent = "";
    say("Fetching…", "busy");
    try {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        const videoId = tab?.url ? videoIdFrom(tab.url) : undefined;
        if (!videoId) {
            say("Open a YouTube video first — this only works on a watch page.", "bad");
            return;
        }
        const { url, init } = playerRequest(videoId);
        const player = await fetchInPage(tab.id, url, init);
        if (!player.ok)
            throw new NotPlayableError(`YouTube refused the request (HTTP ${player.status}).`);
        const payload = JSON.parse(player.body);
        const choice = pickTrack(payload, videoId);
        const track = await fetchInPage(tab.id, choice.track.baseUrl, {});
        const { episode, warning, trackLanguage, trackIsAutoGenerated } = buildEpisode(payload, track.body, videoId, choice);
        await navigator.clipboard.writeText(formatForClipboard(episode));
        const words = episode.segments.reduce((n, s) => n + s.text.split(/\s+/).length, 0);
        say(`Copied — ${words.toLocaleString()} words.`, "good");
        details.textContent =
            warning ??
                `${trackLanguage}${trackIsAutoGenerated ? " · auto-generated" : " · human-written"}` +
                    `${episode.chapters.length ? ` · ${episode.chapters.length} chapters` : ""}`;
    }
    catch (error) {
        if (error instanceof NoCaptionsError || error instanceof NotPlayableError) {
            say(error.message, "bad");
        }
        else {
            say(`Something went wrong: ${String(error)}`, "bad");
        }
    }
    finally {
        button.disabled = false;
    }
});
