#!/usr/bin/env node
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { formatForClipboard } from "./format/formatForClipboard.js";
import { fetchEpisode, NoCaptionsError, NotPlayableError } from "./youtube/fetchEpisode.js";
import { videoIdFrom } from "./youtube/videoId.js";

const USAGE = `
yttranscribe — copy a YouTube episode's transcript

  yttranscribe <url|videoId> [...]        write transcripts to stdout
  yttranscribe <url> --out <dir>          write <date>-<title>.md into <dir>

Options
  --out <dir>   Write a Markdown file per episode instead of printing.
  --quiet       Suppress progress notes on stderr.
`;

/** Filesystem-safe, sorts by episode date. */
function fileNameFor(title: string, publishedAt: string | undefined): string {
  const slug = title
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `${publishedAt ?? "undated"}-${slug}.md`;
}

async function main(argv: string[]): Promise<number> {
  const args = argv.slice(2);
  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    process.stdout.write(USAGE);
    return args.length === 0 ? 1 : 0;
  }

  const quiet = args.includes("--quiet");
  const outIndex = args.indexOf("--out");
  const outDir = outIndex === -1 ? undefined : args[outIndex + 1];
  if (outIndex !== -1 && !outDir) {
    process.stderr.write("--out needs a directory.\n");
    return 1;
  }

  const outValueIndex = outIndex === -1 ? -1 : outIndex + 1;
  const targets = args.filter((arg, i) => !arg.startsWith("--") && i !== outValueIndex);
  const note = (message: string): void => {
    if (!quiet) process.stderr.write(`${message}\n`);
  };

  let failures = 0;

  for (const target of targets) {
    const videoId = videoIdFrom(target);
    if (!videoId) {
      process.stderr.write(`Not a YouTube video: ${target}\n`);
      failures++;
      continue;
    }

    try {
      note(`Fetching ${videoId}…`);
      const { episode, warning, trackLanguage, trackIsAutoGenerated } =
        await fetchEpisode(videoId);

      if (warning) process.stderr.write(`Warning: ${warning}\n`);

      const words = episode.segments.reduce(
        (total, segment) => total + segment.text.split(/\s+/).length,
        0,
      );
      note(
        `  ${episode.title} — ${words.toLocaleString()} words, ` +
          `${trackLanguage}${trackIsAutoGenerated ? " (auto-generated)" : ""}`,
      );

      const markdown = formatForClipboard(episode);

      if (outDir) {
        const path = join(outDir, fileNameFor(episode.title, episode.publishedAt));
        await mkdir(dirname(path), { recursive: true });
        await writeFile(path, markdown, "utf8");
        note(`  → ${path}`);
      } else {
        process.stdout.write(markdown + "\n");
      }
    } catch (error) {
      failures++;
      if (error instanceof NoCaptionsError) {
        process.stderr.write(`${videoId}: ${error.message}\n`);
      } else if (error instanceof NotPlayableError) {
        process.stderr.write(`${videoId}: ${error.message}\n`);
      } else {
        process.stderr.write(`${videoId}: ${String(error)}\n`);
      }
    }
  }

  return failures > 0 ? 1 : 0;
}

main(process.argv).then(
  (code) => process.exit(code),
  (error: unknown) => {
    process.stderr.write(`${String(error)}\n`);
    process.exit(1);
  },
);
